apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: jobset
    control-plane: controller-manager
  name: jobset-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: jobset
  name: jobset-webhook-service
  namespace: jobset-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: jobset-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jobset-webhook-service
        namespace: jobset-system
        path: /mutate-jobset-x-k8s-io-v1alpha2-jobset
    failurePolicy: Fail
    name: mjobset.kb.io
    rules:
      - apiGroups:
          - jobset.x-k8s.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - jobsets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jobset-webhook-service
        namespace: jobset-system
        path: /mutate--v1-pod
    failurePolicy: Fail
    name: mpod.kb.io
    objectSelector:
      matchExpressions:
        - key: jobset.sigs.k8s.io/jobset-name
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: jobset-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jobset-webhook-service
        namespace: jobset-system
        path: /validate-jobset-x-k8s-io-v1alpha2-jobset
    failurePolicy: Fail
    name: vjobset.kb.io
    rules:
      - apiGroups:
          - jobset.x-k8s.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - jobsets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jobset-webhook-service
        namespace: jobset-system
        path: /validate--v1-pod
    failurePolicy: Fail
    name: vpod.kb.io
    objectSelector:
      matchExpressions:
        - key: jobset.sigs.k8s.io/jobset-name
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
