apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobset-controller-manager
  namespace: jobset-system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - "--config=/jobset_manager_config.yaml"
          volumeMounts:
            - name: jobset-manager-config
              mountPath: /jobset_manager_config.yaml
              subPath: jobset_manager_config.yaml
              readOnly: true
      volumes:
        - name: jobset-manager-config
          configMap:
            name: jobset-manager-config
