# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SchedulingV1beta1PodGroupCondition(BaseModel):
    """
    PodGroupCondition contains details for the current state of this pod group.
    """ # noqa: E501
    last_transition_time: Optional[datetime] = Field(default=None, description="Last time the phase transitioned from another to current phase.", alias="lastTransitionTime")
    message: Optional[StrictStr] = Field(default=None, description="Human-readable message indicating details about last transition.")
    reason: Optional[StrictStr] = Field(default=None, description="Unique, one-word, CamelCase reason for the phase's last transition.")
    status: Optional[StrictStr] = Field(default=None, description="Status is the status of the condition.")
    transition_id: Optional[StrictStr] = Field(default=None, description="The ID of condition transition.", alias="transitionID")
    type: Optional[StrictStr] = Field(default=None, description="Type is the type of the condition")
    __properties: ClassVar[List[str]] = ["lastTransitionTime", "message", "reason", "status", "transitionID", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchedulingV1beta1PodGroupCondition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchedulingV1beta1PodGroupCondition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lastTransitionTime": obj.get("lastTransitionTime"),
            "message": obj.get("message"),
            "reason": obj.get("reason"),
            "status": obj.get("status"),
            "transitionID": obj.get("transitionID"),
            "type": obj.get("type")
        })
        return _obj


