# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.scheduling_v1beta1_pod_group_condition import SchedulingV1beta1PodGroupCondition
from typing import Optional, Set
from typing_extensions import Self

class SchedulingV1beta1PodGroupStatus(BaseModel):
    """
    PodGroupStatus represents the current state of a pod group.
    """ # noqa: E501
    conditions: Optional[List[SchedulingV1beta1PodGroupCondition]] = Field(default=None, description="The conditions of PodGroup.")
    failed: Optional[StrictInt] = Field(default=None, description="The number of pods which reached phase Failed.")
    phase: Optional[StrictStr] = Field(default=None, description="Current phase of PodGroup.")
    running: Optional[StrictInt] = Field(default=None, description="The number of actively running pods.")
    succeeded: Optional[StrictInt] = Field(default=None, description="The number of pods which reached phase Succeeded.")
    __properties: ClassVar[List[str]] = ["conditions", "failed", "phase", "running", "succeeded"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchedulingV1beta1PodGroupStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item_conditions in self.conditions:
                if _item_conditions:
                    _items.append(_item_conditions.to_dict())
            _dict['conditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchedulingV1beta1PodGroupStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditions": [SchedulingV1beta1PodGroupCondition.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "failed": obj.get("failed"),
            "phase": obj.get("phase"),
            "running": obj.get("running"),
            "succeeded": obj.get("succeeded")
        })
        return _obj


