# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.trainer_v1alpha1_bayesian_algorithm import TrainerV1alpha1BayesianAlgorithm
from kubeflow_trainer_api.models.trainer_v1alpha1_custom_algorithm import TrainerV1alpha1CustomAlgorithm
from kubeflow_trainer_api.models.trainer_v1alpha1_random_algorithm import TrainerV1alpha1RandomAlgorithm
from kubeflow_trainer_api.models.trainer_v1alpha1_setting_kv import TrainerV1alpha1SettingKV
from kubeflow_trainer_api.models.trainer_v1alpha1_tpe_algorithm import TrainerV1alpha1TPEAlgorithm
from typing import Optional, Set
from typing_extensions import Self

class TrainerV1alpha1SearchAlgorithm(BaseModel):
    """
    SearchAlgorithm defines the hyperparameter sampling configuration.
    """ # noqa: E501
    bayesian: Optional[TrainerV1alpha1BayesianAlgorithm] = None
    custom: Optional[TrainerV1alpha1CustomAlgorithm] = Field(default=None, description="Custom acts as an escape hatch for arbitrary or proprietary samplers.")
    grid: Optional[Dict[str, Any]] = Field(default=None, description="GridAlgorithm is intentionally empty; step-intervals are derived from SearchSpace.Int.Step.")
    provider: Optional[StrictStr] = Field(default=None, description="Provider specifies the backend suggestion engine. Defaults to \"optuna\" if omitted.")
    provider_settings: Optional[List[TrainerV1alpha1SettingKV]] = Field(default=None, description="ProviderSettings passes raw engine kwargs down to the backend microservice.", alias="providerSettings")
    random: Optional[TrainerV1alpha1RandomAlgorithm] = None
    tpe: Optional[TrainerV1alpha1TPEAlgorithm] = None
    __properties: ClassVar[List[str]] = ["bayesian", "custom", "grid", "provider", "providerSettings", "random", "tpe"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1SearchAlgorithm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bayesian
        if self.bayesian:
            _dict['bayesian'] = self.bayesian.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom
        if self.custom:
            _dict['custom'] = self.custom.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in provider_settings (list)
        _items = []
        if self.provider_settings:
            for _item_provider_settings in self.provider_settings:
                if _item_provider_settings:
                    _items.append(_item_provider_settings.to_dict())
            _dict['providerSettings'] = _items
        # override the default output from pydantic by calling `to_dict()` of random
        if self.random:
            _dict['random'] = self.random.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tpe
        if self.tpe:
            _dict['tpe'] = self.tpe.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1SearchAlgorithm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bayesian": TrainerV1alpha1BayesianAlgorithm.from_dict(obj["bayesian"]) if obj.get("bayesian") is not None else None,
            "custom": TrainerV1alpha1CustomAlgorithm.from_dict(obj["custom"]) if obj.get("custom") is not None else None,
            "grid": obj.get("grid"),
            "provider": obj.get("provider"),
            "providerSettings": [TrainerV1alpha1SettingKV.from_dict(_item) for _item in obj["providerSettings"]] if obj.get("providerSettings") is not None else None,
            "random": TrainerV1alpha1RandomAlgorithm.from_dict(obj["random"]) if obj.get("random") is not None else None,
            "tpe": TrainerV1alpha1TPEAlgorithm.from_dict(obj["tpe"]) if obj.get("tpe") is not None else None
        })
        return _obj


