# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.trainer_v1alpha1_optimization_storage import TrainerV1alpha1OptimizationStorage
from typing import Optional, Set
from typing_extensions import Self

class TrainerV1alpha1TrialConfig(BaseModel):
    """
    TrialConfig controls the orchestration of the trials.
    """ # noqa: E501
    max_failed_trials: Optional[StrictInt] = Field(default=None, alias="maxFailedTrials")
    num_trials: Optional[StrictInt] = Field(default=None, alias="numTrials")
    parallel_trials: Optional[StrictInt] = Field(default=None, alias="parallelTrials")
    storage: Optional[TrainerV1alpha1OptimizationStorage] = Field(default=None, description="Storage configures where suspended trials persist their checkpoints.")
    __properties: ClassVar[List[str]] = ["maxFailedTrials", "numTrials", "parallelTrials", "storage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1TrialConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of storage
        if self.storage:
            _dict['storage'] = self.storage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1TrialConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maxFailedTrials": obj.get("maxFailedTrials"),
            "numTrials": obj.get("numTrials"),
            "parallelTrials": obj.get("parallelTrials"),
            "storage": TrainerV1alpha1OptimizationStorage.from_dict(obj["storage"]) if obj.get("storage") is not None else None
        })
        return _obj


