---
# Chart testing configuration for kubeflow-trainer

# Directories containing charts to test
chart-dirs:
  - charts

# Charts to exclude from testing (if any)
excluded-charts: []

# Target branch for comparison (used for detecting changes)
target-branch: master

# Version increment checking
# Set to false for initial setup, enable later for strict versioning
check-version-increment: false

# Schema validation settings
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true

# Helm configuration
helm-extra-args: --timeout 300s --wait --debug

# Helm extra set args for testing
helm-extra-set-args: --set=jobset.install=true --set=replicaCount=1 --set=image.pullPolicy=IfNotPresent

# Default namespace for chart installations
namespace: kubeflow-system

# Additional commands to run for each chart
additional-commands:
  - helm dependency update {{ .Path }}
  - helm template {{ .Path }} --debug --namespace kubeflow-system --dry-run
  - helm lint {{ .Path }}

# Debug settings
debug: true

# Skip cleanup after testing (useful for debugging)
skip-clean-up: false

# Test upgrades (install chart, then upgrade)
upgrade: true

# Print config for debugging
print-config: true

# Helm dependency build before testing
helm-dependency-extra-args: --skip-refresh

# Test configuration
test-extra-args: --logs

# Release name template
release-label-selector: app.kubernetes.io/instance={{ .Release.Name }}
