---
# Chart testing configuration for kubeflow-trainer

# Directories containing charts to test
chart-dirs:
  - charts

# Charts to exclude from testing (if any)
excluded-charts: []

# Target branch for comparison (used for detecting changes)
target-branch: main

# Remote repository for comparison
remote: origin

# Version increment checking
# Set to false for initial setup, enable later for strict versioning
check-version-increment: false

# Schema validation settings
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true

# Helm configuration - increase timeout for slow installations
helm-extra-args: --timeout 600s --wait --debug

# Helm extra set args for testing
# Note: jobset.install=false because we install JobSet manually
helm-extra-set-args: --set=jobset.install=false --set=replicaCount=1 --set=image.pullPolicy=IfNotPresent --set=resources.limits.cpu=100m --set=resources.limits.memory=128Mi

# Debug settings
debug: true

# Skip cleanup after testing for debugging (will be cleaned up in workflow)
skip-clean-up: true

# Test upgrades (install chart, then upgrade)
upgrade: false

# Print config for debugging
print-config: true

# Skip dependency build since we handle JobSet manually
helm-dependency-extra-args: --skip-refresh

# Test configuration with increased verbosity
test-extra-args: --logs --debug
