apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We can't set namespace in the overlays since we use remote JobSet manifests in the resources.
namespace: kubeflow-system
resources:
  - ./crds
  - ./rbac
  - ./webhook
  - ./manager
