# TODO (andreyvelich): Change this to DeepSpeed or MLX runtime.
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: mpi-distributed
  labels:
    trainer.kubeflow.org/phase: pre-training
spec:
  mlPolicy:
    numNodes: 1
    mpi:
      numProcPerNode: 1
      mpiImplementation: OpenMPI
      sshAuthMountPath: /home/mpiuser/.ssh
  template:
    spec:
      network:
        publishNotReadyAddresses: false
      successPolicy:
        operator: All
        targetReplicatedJobs:
          - launcher
      replicatedJobs:
        - name: launcher
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: launcher
                      image: mpioperator/mpi-pi:openmpi
                      securityContext:
                        runAsUser: 1000
                      command:
                        - mpirun
                      args:
                        - /home/mpiuser/pi
        - name: trainer-node
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: trainer-node
                      image: mpioperator/mpi-pi:openmpi
                      securityContext:
                        runAsUser: 1000
                      command:
                        - /usr/sbin/sshd
                      args:
                        - -De
                        - -f
                        - /home/mpiuser/.sshd_config
                      readinessProbe:
                        tcpSocket:
                          port: 2222
                        initialDelaySeconds: 5
