# TODO (andreyvelich): Change this to DeepSpeed or MLX runtime.
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: mpi-distributed
  labels:
    trainer.kubeflow.org/phase: pre-training
spec:
  mlPolicy:
    numNodes: 1
    mpi:
      numProcPerNode: 1
      mpiImplementation: OpenMPI
      sshAuthMountPath: /root/.ssh
  template:
    spec:
      replicatedJobs:
        - name: launcher
          template:
            spec:
              template:
                spec:
                  # TODO (andreyvelich): Change the command with mpirun.
                  containers:
                    - name: launcher
                      image: busybox
                      command:
                        - /bin/sh
                        - -c
                        - "echo 'launcher runs for 15 seconds' && sleep 15"
        - name: trainer-node
          dependsOn:
            - name: launcher
              status: Ready
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: trainer
                      image: busybox
                      command:
                        - /bin/sh
                        - -c
                        - "echo 'trainer node runs for 15 seconds' && sleep 15"
