# TODO (andreyvelich): Change this to DeepSpeed or MLX runtime.
apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: mpi-distributed
  labels:
    training.kubeflow.org/phase: pre-training
spec:
  mlPolicy:
    numNodes: 1
    mpi:
      numProcPerNode: 1
      mpiImplementation: OpenMPI
      sshAuthMountPath: /root/.ssh
  template:
    spec:
      # TODO (andreyvelich): Use dependsOn when it is released.
      startupPolicy:
        startupPolicyOrder: InOrder
      replicatedJobs:
        - name: launcher
          template:
            spec:
              template:
                spec:
                  # TODO (andreyvelich): Change the command with mpirun.
                  containers:
                    - name: launcher
                      image: busybox
                      command:
                        - /bin/sh
                        - -c
                        - "echo 'launcher runs for 10 seconds' && sleep 100"
        - name: trainer-node
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: trainer
                      image: busybox
                      command:
                        - /bin/sh
                        - -c
                        - "echo 'launcher runs for 10 seconds' && sleep 100"
