# Advanced Example 1: PodSpec Overrides
#
# This example demonstrates pod customization using podTemplateOverrides
# and the Trainer API. It shows the correct way to set resources, env vars,
# node placement, tolerations, and annotations for training pods.
#
# Key points:
#   - podTemplateOverrides is a top-level field under spec (NOT under trainer)
#   - Resources for training nodes are set via spec.trainer.resourcesPerNode
#   - Env vars for the "node" container are set via spec.trainer.env
#     (podTemplateOverrides env is forbidden for the "node" container)
#   - podTemplateOverrides is used for pod-level settings like nodeSelector,
#     tolerations, serviceAccountName, annotations, labels, and volumes
#
# Apply: kubectl apply -f 01-podspec-overrides.yaml
# Check: kubectl describe trainjob podspec-example
# Logs:  kubectl logs -l trainer.kubeflow.org/job-name=podspec-example
# Clean: kubectl delete trainjob podspec-example

apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: podspec-example
  namespace: default
spec:
  runtimeRef:
    apiGroup: trainer.kubeflow.org
    kind: ClusterTrainingRuntime
    name: torch-distributed

  trainer:
    numNodes: 2
    command:
      - python3
      - -c
      - |
        import os
        print(f"Node running with:")
        print(f"  CUSTOM_VAR: {os.getenv('CUSTOM_VAR')}")
        print(f"  TRAINING_MODE: {os.getenv('TRAINING_MODE')}")

    # Env vars for the "node" container must be set here, not in podTemplateOverrides.
    env:
      - name: CUSTOM_VAR
        value: "custom-value"
      - name: TRAINING_MODE
        value: "distributed"
      - name: PYTHONUNBUFFERED
        value: "1"

    # Resources for training nodes are set here, not in podTemplateOverrides.
    resourcesPerNode:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  # podTemplateOverrides is a top-level field under spec.
  # Use it for pod-level settings: nodeSelector, tolerations, annotations, etc.
  podTemplateOverrides:
    - targetJobs:
        - name: node
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
        labels:
          team: ml-platform
          cost-center: research
      spec:
        nodeSelector:
          node-type: training
        tolerations:
          - key: "training-workload"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        serviceAccountName: training-sa
