apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: deepspeed-distributed
  labels:
    trainer.kubeflow.org/accelerator: gpu-tesla-v100-16gb
spec:
  mlPolicy:
    numNodes: 1
    mpi:
      # TODO (andreyvelich): Change num proc to 1 and remove container resources after we
      # allow to override it via TrainJob APIs.
      numProcPerNode: 4
      mpiImplementation: OpenMPI
      sshAuthMountPath: /home/mpiuser/.ssh
      runLauncherAsNode: true
  template:
    spec:
      network:
        publishNotReadyAddresses: true
      successPolicy:
        operator: All
        targetReplicatedJobs:
          - launcher
      replicatedJobs:
        - name: launcher
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: docker.io/andreyvelichkevich/deepspeed-runtime
                      securityContext:
                        runAsUser: 1000
                      command:
                        - mpirun
                        - -n
                        - "1"
                        - bash
                        - -c
                        - |
                          echo "DeepSpeed Distributed Runtime"

                          echo "--------------------------------------"
                          set -e
                          mpirun --version
                          python --version
                          pip list
                      resources:
                        limits:
                          nvidia.com/gpu: 4
        - name: node
          template:
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: docker.io/andreyvelichkevich/deepspeed-runtime
                      securityContext:
                        runAsUser: 1000
                      resources:
                        limits:
                          nvidia.com/gpu: 4
                      command:
                        - /usr/sbin/sshd
                      args:
                        - -De
                        - -f
                        - /home/mpiuser/.sshd_config
                      readinessProbe:
                        tcpSocket:
                          port: 2222
                        initialDelaySeconds: 5
