apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: flux-distributed
  labels:
    trainer.kubeflow.org/framework: flux
spec:
  mlPolicy:
    numNodes: 1
    flux:
      numProcPerNode: 1
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: ubuntu:22.04
