// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMPIJobs implements MPIJobInterface
type fakeMPIJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.MPIJob, *v1.MPIJobList, *kubefloworgv1.MPIJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakeMPIJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.MPIJobInterface {
	return &fakeMPIJobs{
		gentype.NewFakeClientWithListAndApply[*v1.MPIJob, *v1.MPIJobList, *kubefloworgv1.MPIJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("mpijobs"),
			v1.SchemeGroupVersion.WithKind("MPIJob"),
			func() *v1.MPIJob { return &v1.MPIJob{} },
			func() *v1.MPIJobList { return &v1.MPIJobList{} },
			func(dst, src *v1.MPIJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.MPIJobList) []*v1.MPIJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.MPIJobList, items []*v1.MPIJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
