// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeXGBoostJobs implements XGBoostJobInterface
type fakeXGBoostJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.XGBoostJob, *v1.XGBoostJobList, *kubefloworgv1.XGBoostJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakeXGBoostJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.XGBoostJobInterface {
	return &fakeXGBoostJobs{
		gentype.NewFakeClientWithListAndApply[*v1.XGBoostJob, *v1.XGBoostJobList, *kubefloworgv1.XGBoostJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("xgboostjobs"),
			v1.SchemeGroupVersion.WithKind("XGBoostJob"),
			func() *v1.XGBoostJob { return &v1.XGBoostJob{} },
			func() *v1.XGBoostJobList { return &v1.XGBoostJobList{} },
			func(dst, src *v1.XGBoostJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.XGBoostJobList) []*v1.XGBoostJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.XGBoostJobList, items []*v1.XGBoostJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
