// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTFJobs implements TFJobInterface
type fakeTFJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.TFJob, *v1.TFJobList, *kubefloworgv1.TFJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakeTFJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.TFJobInterface {
	return &fakeTFJobs{
		gentype.NewFakeClientWithListAndApply[*v1.TFJob, *v1.TFJobList, *kubefloworgv1.TFJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("tfjobs"),
			v1.SchemeGroupVersion.WithKind("TFJob"),
			func() *v1.TFJob { return &v1.TFJob{} },
			func() *v1.TFJobList { return &v1.TFJobList{} },
			func(dst, src *v1.TFJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.TFJobList) []*v1.TFJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.TFJobList, items []*v1.TFJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
