// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakePaddleJobs implements PaddleJobInterface
type fakePaddleJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.PaddleJob, *v1.PaddleJobList, *kubefloworgv1.PaddleJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakePaddleJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.PaddleJobInterface {
	return &fakePaddleJobs{
		gentype.NewFakeClientWithListAndApply[*v1.PaddleJob, *v1.PaddleJobList, *kubefloworgv1.PaddleJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("paddlejobs"),
			v1.SchemeGroupVersion.WithKind("PaddleJob"),
			func() *v1.PaddleJob { return &v1.PaddleJob{} },
			func() *v1.PaddleJobList { return &v1.PaddleJobList{} },
			func(dst, src *v1.PaddleJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PaddleJobList) []*v1.PaddleJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PaddleJobList, items []*v1.PaddleJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
