// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeJAXJobs implements JAXJobInterface
type fakeJAXJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.JAXJob, *v1.JAXJobList, *kubefloworgv1.JAXJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakeJAXJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.JAXJobInterface {
	return &fakeJAXJobs{
		gentype.NewFakeClientWithListAndApply[*v1.JAXJob, *v1.JAXJobList, *kubefloworgv1.JAXJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("jaxjobs"),
			v1.SchemeGroupVersion.WithKind("JAXJob"),
			func() *v1.JAXJob { return &v1.JAXJob{} },
			func() *v1.JAXJobList { return &v1.JAXJobList{} },
			func(dst, src *v1.JAXJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.JAXJobList) []*v1.JAXJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.JAXJobList, items []*v1.JAXJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
