// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	typedkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/typed/kubeflow.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakePyTorchJobs implements PyTorchJobInterface
type fakePyTorchJobs struct {
	*gentype.FakeClientWithListAndApply[*v1.PyTorchJob, *v1.PyTorchJobList, *kubefloworgv1.PyTorchJobApplyConfiguration]
	Fake *FakeKubeflowV1
}

func newFakePyTorchJobs(fake *FakeKubeflowV1, namespace string) typedkubefloworgv1.PyTorchJobInterface {
	return &fakePyTorchJobs{
		gentype.NewFakeClientWithListAndApply[*v1.PyTorchJob, *v1.PyTorchJobList, *kubefloworgv1.PyTorchJobApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("pytorchjobs"),
			v1.SchemeGroupVersion.WithKind("PyTorchJob"),
			func() *v1.PyTorchJob { return &v1.PyTorchJob{} },
			func() *v1.PyTorchJobList { return &v1.PyTorchJobList{} },
			func(dst, src *v1.PyTorchJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PyTorchJobList) []*v1.PyTorchJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PyTorchJobList, items []*v1.PyTorchJob) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
