// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BestTrialApplyConfiguration represents a declarative configuration of the BestTrial type for use
// with apply.
//
// BestTrial tracks the best performing trial.
// Kept minimal for MVP; users can inspect the specific Trial/TrainJob for exact metrics and settings.
type BestTrialApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	// optimalParameters is a list of the hyperparameter assignments that won.
	OptimalParameters []ParameterAssignmentApplyConfiguration `json:"optimalParameters,omitempty"`
}

// BestTrialApplyConfiguration constructs a declarative configuration of the BestTrial type for use with
// apply.
func BestTrial() *BestTrialApplyConfiguration {
	return &BestTrialApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BestTrialApplyConfiguration) WithName(value string) *BestTrialApplyConfiguration {
	b.Name = &value
	return b
}

// WithOptimalParameters adds the given value to the OptimalParameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OptimalParameters field.
func (b *BestTrialApplyConfiguration) WithOptimalParameters(values ...*ParameterAssignmentApplyConfiguration) *BestTrialApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOptimalParameters")
		}
		b.OptimalParameters = append(b.OptimalParameters, *values[i])
	}
	return b
}
