// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BestTrialApplyConfiguration represents a declarative configuration of the BestTrial type for use
// with apply.
//
// BestTrial tracks the parameters of the highest performing trial.
type BestTrialApplyConfiguration struct {
	Parameters []ParameterAssignmentApplyConfiguration `json:"parameters,omitempty"`
}

// BestTrialApplyConfiguration constructs a declarative configuration of the BestTrial type for use with
// apply.
func BestTrial() *BestTrialApplyConfiguration {
	return &BestTrialApplyConfiguration{}
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *BestTrialApplyConfiguration) WithParameters(values ...*ParameterAssignmentApplyConfiguration) *BestTrialApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}
