// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CategoricalSpaceApplyConfiguration represents a declarative configuration of the CategoricalSpace type for use
// with apply.
//
// CategoricalSpace defines a search space over a discrete set of unordered strings.
type CategoricalSpaceApplyConfiguration struct {
	List []string `json:"list,omitempty"`
}

// CategoricalSpaceApplyConfiguration constructs a declarative configuration of the CategoricalSpace type for use with
// apply.
func CategoricalSpace() *CategoricalSpaceApplyConfiguration {
	return &CategoricalSpaceApplyConfiguration{}
}

// WithList adds the given value to the List field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the List field.
func (b *CategoricalSpaceApplyConfiguration) WithList(values ...string) *CategoricalSpaceApplyConfiguration {
	for i := range values {
		b.List = append(b.List, values[i])
	}
	return b
}
