// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EarlyStoppingApplyConfiguration represents a declarative configuration of the EarlyStopping type for use
// with apply.
//
// EarlyStopping defines the configuration for pruning unpromising trials.
type EarlyStoppingApplyConfiguration struct {
	// Name of the early stopping algorithm (e.g., median, asha).
	Name     *string                       `json:"name,omitempty"`
	Settings []SettingKVApplyConfiguration `json:"settings,omitempty"`
}

// EarlyStoppingApplyConfiguration constructs a declarative configuration of the EarlyStopping type for use with
// apply.
func EarlyStopping() *EarlyStoppingApplyConfiguration {
	return &EarlyStoppingApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EarlyStoppingApplyConfiguration) WithName(value string) *EarlyStoppingApplyConfiguration {
	b.Name = &value
	return b
}

// WithSettings adds the given value to the Settings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Settings field.
func (b *EarlyStoppingApplyConfiguration) WithSettings(values ...*SettingKVApplyConfiguration) *EarlyStoppingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSettings")
		}
		b.Settings = append(b.Settings, *values[i])
	}
	return b
}
