/*
Copyright The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
)

// LogNormalSpaceApplyConfiguration represents a declarative configuration of the LogNormalSpace type for use
// with apply.
//
// LogNormalSpace defines a continuous log-normal distribution, that is a
// distribution whose logarithm is normal with center Mean and standard
// deviation StdDev. Mean and StdDev are therefore expressed in log space, so
// Mean may be negative while the sampled values are always positive.
type LogNormalSpaceApplyConfiguration struct {
	// mean is the center of the log-normal search space, in log space.
	Mean *trainerv1alpha1.Double `json:"mean,omitempty"`
	// stdDev is the standard deviation of the log-normal search space, in log space.
	StdDev *trainerv1alpha1.Double `json:"stdDev,omitempty"`
}

// LogNormalSpaceApplyConfiguration constructs a declarative configuration of the LogNormalSpace type for use with
// apply.
func LogNormalSpace() *LogNormalSpaceApplyConfiguration {
	return &LogNormalSpaceApplyConfiguration{}
}

// WithMean sets the Mean field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mean field is set to the value of the last call.
func (b *LogNormalSpaceApplyConfiguration) WithMean(value trainerv1alpha1.Double) *LogNormalSpaceApplyConfiguration {
	b.Mean = &value
	return b
}

// WithStdDev sets the StdDev field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdDev field is set to the value of the last call.
func (b *LogNormalSpaceApplyConfiguration) WithStdDev(value trainerv1alpha1.Double) *LogNormalSpaceApplyConfiguration {
	b.StdDev = &value
	return b
}
