// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NormalSpaceApplyConfiguration represents a declarative configuration of the NormalSpace type for use
// with apply.
//
// NormalSpace defines a continuous normal (Gaussian) distribution.
type NormalSpaceApplyConfiguration struct {
	Mean   *string `json:"mean,omitempty"`
	StdDev *string `json:"stdDev,omitempty"`
}

// NormalSpaceApplyConfiguration constructs a declarative configuration of the NormalSpace type for use with
// apply.
func NormalSpace() *NormalSpaceApplyConfiguration {
	return &NormalSpaceApplyConfiguration{}
}

// WithMean sets the Mean field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mean field is set to the value of the last call.
func (b *NormalSpaceApplyConfiguration) WithMean(value string) *NormalSpaceApplyConfiguration {
	b.Mean = &value
	return b
}

// WithStdDev sets the StdDev field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdDev field is set to the value of the last call.
func (b *NormalSpaceApplyConfiguration) WithStdDev(value string) *NormalSpaceApplyConfiguration {
	b.StdDev = &value
	return b
}
