// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OptimizationJobSpecApplyConfiguration represents a declarative configuration of the OptimizationJobSpec type for use
// with apply.
//
// OptimizationJobSpec defines the desired state of OptimizationJob.
type OptimizationJobSpecApplyConfiguration struct {
	Objectives []ObjectiveApplyConfiguration `json:"objectives,omitempty"`
	// SearchAlgorithm explicitly separates initial sampling from mid-run pruning.
	SearchAlgorithm *SearchAlgorithmApplyConfiguration `json:"searchAlgorithm,omitempty"`
	Parameters      []ParameterApplyConfiguration      `json:"parameters,omitempty"`
	TrialConfig     *TrialConfigApplyConfiguration     `json:"trialConfig,omitempty"`
	// TrainJobTemplate wraps the underlying TrainJob workload and its metadata.
	TrainJobTemplate *TrainJobTemplateSpecApplyConfiguration `json:"trainJobTemplate,omitempty"`
}

// OptimizationJobSpecApplyConfiguration constructs a declarative configuration of the OptimizationJobSpec type for use with
// apply.
func OptimizationJobSpec() *OptimizationJobSpecApplyConfiguration {
	return &OptimizationJobSpecApplyConfiguration{}
}

// WithObjectives adds the given value to the Objectives field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Objectives field.
func (b *OptimizationJobSpecApplyConfiguration) WithObjectives(values ...*ObjectiveApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjectives")
		}
		b.Objectives = append(b.Objectives, *values[i])
	}
	return b
}

// WithSearchAlgorithm sets the SearchAlgorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchAlgorithm field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithSearchAlgorithm(value *SearchAlgorithmApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	b.SearchAlgorithm = value
	return b
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *OptimizationJobSpecApplyConfiguration) WithParameters(values ...*ParameterApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}

// WithTrialConfig sets the TrialConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrialConfig field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithTrialConfig(value *TrialConfigApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	b.TrialConfig = value
	return b
}

// WithTrainJobTemplate sets the TrainJobTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrainJobTemplate field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithTrainJobTemplate(value *TrainJobTemplateSpecApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	b.TrainJobTemplate = value
	return b
}
