// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OptimizationStorageApplyConfiguration represents a declarative configuration of the OptimizationStorage type for use
// with apply.
//
// OptimizationStorage defines the persistent layer for trial checkpoints and state recovery.
type OptimizationStorageApplyConfiguration struct {
	// StorageUri is the remote object storage path (e.g., s3://my-bucket/experiments).
	StorageUri *string `json:"storageUri,omitempty"`
	// PvcName is the name of an existing PersistentVolumeClaim in the same namespace.
	PvcName *string `json:"pvcName,omitempty"`
}

// OptimizationStorageApplyConfiguration constructs a declarative configuration of the OptimizationStorage type for use with
// apply.
func OptimizationStorage() *OptimizationStorageApplyConfiguration {
	return &OptimizationStorageApplyConfiguration{}
}

// WithStorageUri sets the StorageUri field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageUri field is set to the value of the last call.
func (b *OptimizationStorageApplyConfiguration) WithStorageUri(value string) *OptimizationStorageApplyConfiguration {
	b.StorageUri = &value
	return b
}

// WithPvcName sets the PvcName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PvcName field is set to the value of the last call.
func (b *OptimizationStorageApplyConfiguration) WithPvcName(value string) *OptimizationStorageApplyConfiguration {
	b.PvcName = &value
	return b
}
