// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// OptimizationJobStatusApplyConfiguration represents a declarative configuration of the OptimizationJobStatus type for use
// with apply.
//
// OptimizationJobStatus defines the observed state of OptimizationJob.
type OptimizationJobStatusApplyConfiguration struct {
	Phase      *trainerv1alpha1.OptimizationJobPhase `json:"phase,omitempty"`
	Conditions []v1.ConditionApplyConfiguration      `json:"conditions,omitempty"`
	Active     *int32                                `json:"active,omitempty"`
	// Suspended tracks trials that are paused by dynamic algorithms (e.g., PBT).
	Suspended *int32 `json:"suspended,omitempty"`
	Succeeded *int32 `json:"succeeded,omitempty"`
	Failed    *int32 `json:"failed,omitempty"`
	// BestTrial caches the highest performing trial based on the Objective.
	BestTrial *BestTrialApplyConfiguration `json:"bestTrial,omitempty"`
}

// OptimizationJobStatusApplyConfiguration constructs a declarative configuration of the OptimizationJobStatus type for use with
// apply.
func OptimizationJobStatus() *OptimizationJobStatusApplyConfiguration {
	return &OptimizationJobStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithPhase(value trainerv1alpha1.OptimizationJobPhase) *OptimizationJobStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OptimizationJobStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *OptimizationJobStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithActive(value int32) *OptimizationJobStatusApplyConfiguration {
	b.Active = &value
	return b
}

// WithSuspended sets the Suspended field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspended field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithSuspended(value int32) *OptimizationJobStatusApplyConfiguration {
	b.Suspended = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithSucceeded(value int32) *OptimizationJobStatusApplyConfiguration {
	b.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithFailed(value int32) *OptimizationJobStatusApplyConfiguration {
	b.Failed = &value
	return b
}

// WithBestTrial sets the BestTrial field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BestTrial field is set to the value of the last call.
func (b *OptimizationJobStatusApplyConfiguration) WithBestTrial(value *BestTrialApplyConfiguration) *OptimizationJobStatusApplyConfiguration {
	b.BestTrial = value
	return b
}
