// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SearchSpaceApplyConfiguration represents a declarative configuration of the SearchSpace type for use
// with apply.
//
// SearchSpace defines the type and exact boundaries for the algorithm to search.
type SearchSpaceApplyConfiguration struct {
	Type *string  `json:"type,omitempty"`
	Max  *string  `json:"max,omitempty"`
	Min  *string  `json:"min,omitempty"`
	List []string `json:"list,omitempty"`
}

// SearchSpaceApplyConfiguration constructs a declarative configuration of the SearchSpace type for use with
// apply.
func SearchSpace() *SearchSpaceApplyConfiguration {
	return &SearchSpaceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithType(value string) *SearchSpaceApplyConfiguration {
	b.Type = &value
	return b
}

// WithMax sets the Max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Max field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithMax(value string) *SearchSpaceApplyConfiguration {
	b.Max = &value
	return b
}

// WithMin sets the Min field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Min field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithMin(value string) *SearchSpaceApplyConfiguration {
	b.Min = &value
	return b
}

// WithList adds the given value to the List field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the List field.
func (b *SearchSpaceApplyConfiguration) WithList(values ...string) *SearchSpaceApplyConfiguration {
	for i := range values {
		b.List = append(b.List, values[i])
	}
	return b
}
