// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SearchAlgorithmApplyConfiguration represents a declarative configuration of the SearchAlgorithm type for use
// with apply.
//
// SearchAlgorithm defines the hyperparameter sampling configuration.
type SearchAlgorithmApplyConfiguration struct {
	// Provider specifies the backend suggestion engine. Defaults to "optuna" if omitted.
	Provider *string                            `json:"provider,omitempty"`
	Random   *RandomAlgorithmApplyConfiguration `json:"random,omitempty"`
	// ProviderSettings passes raw engine kwargs down to the backend microservice.
	ProviderSettings []SettingKVApplyConfiguration `json:"providerSettings,omitempty"`
}

// SearchAlgorithmApplyConfiguration constructs a declarative configuration of the SearchAlgorithm type for use with
// apply.
func SearchAlgorithm() *SearchAlgorithmApplyConfiguration {
	return &SearchAlgorithmApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *SearchAlgorithmApplyConfiguration) WithProvider(value string) *SearchAlgorithmApplyConfiguration {
	b.Provider = &value
	return b
}

// WithRandom sets the Random field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Random field is set to the value of the last call.
func (b *SearchAlgorithmApplyConfiguration) WithRandom(value *RandomAlgorithmApplyConfiguration) *SearchAlgorithmApplyConfiguration {
	b.Random = value
	return b
}

// WithProviderSettings adds the given value to the ProviderSettings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProviderSettings field.
func (b *SearchAlgorithmApplyConfiguration) WithProviderSettings(values ...*SettingKVApplyConfiguration) *SearchAlgorithmApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProviderSettings")
		}
		b.ProviderSettings = append(b.ProviderSettings, *values[i])
	}
	return b
}
