// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SearchSpaceApplyConfiguration represents a declarative configuration of the SearchSpace type for use
// with apply.
//
// SearchSpace acts as a Discriminated Union (OneOf) supporting flexible statistical distributions.
type SearchSpaceApplyConfiguration struct {
	Uniform     *UniformSpaceApplyConfiguration     `json:"uniform,omitempty"`
	LogUniform  *LogUniformSpaceApplyConfiguration  `json:"logUniform,omitempty"`
	Normal      *NormalSpaceApplyConfiguration      `json:"normal,omitempty"`
	LogNormal   *LogNormalSpaceApplyConfiguration   `json:"logNormal,omitempty"`
	Int         *IntSpaceApplyConfiguration         `json:"int,omitempty"`
	Categorical *CategoricalSpaceApplyConfiguration `json:"categorical,omitempty"`
}

// SearchSpaceApplyConfiguration constructs a declarative configuration of the SearchSpace type for use with
// apply.
func SearchSpace() *SearchSpaceApplyConfiguration {
	return &SearchSpaceApplyConfiguration{}
}

// WithUniform sets the Uniform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uniform field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithUniform(value *UniformSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.Uniform = value
	return b
}

// WithLogUniform sets the LogUniform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogUniform field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithLogUniform(value *LogUniformSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.LogUniform = value
	return b
}

// WithNormal sets the Normal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Normal field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithNormal(value *NormalSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.Normal = value
	return b
}

// WithLogNormal sets the LogNormal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogNormal field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithLogNormal(value *LogNormalSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.LogNormal = value
	return b
}

// WithInt sets the Int field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Int field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithInt(value *IntSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.Int = value
	return b
}

// WithCategorical sets the Categorical field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Categorical field is set to the value of the last call.
func (b *SearchSpaceApplyConfiguration) WithCategorical(value *CategoricalSpaceApplyConfiguration) *SearchSpaceApplyConfiguration {
	b.Categorical = value
	return b
}
