// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
)

// SearchAlgorithmApplyConfiguration represents a declarative configuration of the SearchAlgorithm type for use
// with apply.
//
// SearchAlgorithm defines the hyperparameter sampling configuration.
type SearchAlgorithmApplyConfiguration struct {
	Random   *RandomAlgorithmApplyConfiguration   `json:"random,omitempty"`
	Grid     *trainerv1alpha1.GridAlgorithm       `json:"grid,omitempty"`
	Bayesian *BayesianAlgorithmApplyConfiguration `json:"bayesian,omitempty"`
}

// SearchAlgorithmApplyConfiguration constructs a declarative configuration of the SearchAlgorithm type for use with
// apply.
func SearchAlgorithm() *SearchAlgorithmApplyConfiguration {
	return &SearchAlgorithmApplyConfiguration{}
}

// WithRandom sets the Random field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Random field is set to the value of the last call.
func (b *SearchAlgorithmApplyConfiguration) WithRandom(value *RandomAlgorithmApplyConfiguration) *SearchAlgorithmApplyConfiguration {
	b.Random = value
	return b
}

// WithGrid sets the Grid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Grid field is set to the value of the last call.
func (b *SearchAlgorithmApplyConfiguration) WithGrid(value trainerv1alpha1.GridAlgorithm) *SearchAlgorithmApplyConfiguration {
	b.Grid = &value
	return b
}

// WithBayesian sets the Bayesian field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bayesian field is set to the value of the last call.
func (b *SearchAlgorithmApplyConfiguration) WithBayesian(value *BayesianAlgorithmApplyConfiguration) *SearchAlgorithmApplyConfiguration {
	b.Bayesian = value
	return b
}
