// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TPEAlgorithmApplyConfiguration represents a declarative configuration of the TPEAlgorithm type for use
// with apply.
type TPEAlgorithmApplyConfiguration struct {
	InitialTrials *int32 `json:"initialTrials,omitempty"`
	EICandidates  *int32 `json:"eiCandidates,omitempty"`
	Seed          *int64 `json:"seed,omitempty"`
}

// TPEAlgorithmApplyConfiguration constructs a declarative configuration of the TPEAlgorithm type for use with
// apply.
func TPEAlgorithm() *TPEAlgorithmApplyConfiguration {
	return &TPEAlgorithmApplyConfiguration{}
}

// WithInitialTrials sets the InitialTrials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialTrials field is set to the value of the last call.
func (b *TPEAlgorithmApplyConfiguration) WithInitialTrials(value int32) *TPEAlgorithmApplyConfiguration {
	b.InitialTrials = &value
	return b
}

// WithEICandidates sets the EICandidates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EICandidates field is set to the value of the last call.
func (b *TPEAlgorithmApplyConfiguration) WithEICandidates(value int32) *TPEAlgorithmApplyConfiguration {
	b.EICandidates = &value
	return b
}

// WithSeed sets the Seed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Seed field is set to the value of the last call.
func (b *TPEAlgorithmApplyConfiguration) WithSeed(value int64) *TPEAlgorithmApplyConfiguration {
	b.Seed = &value
	return b
}
