name: Notebook test template
description: A composite action to setup and run example notebooks using Papermill

inputs:
  kubernetes-version:
    required: true
    description: kubernetes version
  python-version:
    required: false
    description: Python version
    # Most latest supporting version
    default: "3.10"
  papermill-args-yaml:
    description: 'Additional arguments to pass to Papermill in yaml format'
    required: false
    default: ""
  notebook-input:
    description: 'Path to the input notebook'
    required: true
  notebook-output:
    description: 'Path to save the output notebook'
    required: true

runs:
  using: composite
  steps:
    - name: Free-Up Disk Space
      uses: ./.github/workflows/free-up-disk-space

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install jupyter ipykernel papermill==2.2.0

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
      with:
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: training-operator-cluster
        kubectl_version: ${{ inputs.kubernetes-version }}

    - name: Build training-operator
      shell: bash
      run: |
        ./scripts/gha/build-image.sh
      env:
        TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test

    - name: Deploy training operator
      shell: bash
      run: |
        ./scripts/gha/setup-training-operator.sh
        docker system prune -a -f
        docker system df
        df -h
      env:
        KIND_CLUSTER: training-operator-cluster
        TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test
        GANG_SCHEDULER_NAME: "none"
        KUBERNETES_VERSION: ${{ inputs.kubernetes-version }}

    - name: Print Papermill Args
      shell: bash
      run: echo "${{ github.event.inputs.papermill-args-yaml }}"

    - name: Run Jupyter Notebook with Papermill
      shell: bash
      run: |
        papermill ${{ inputs.notebook-input }} ${{ inputs.notebook-output }} --parameters_yaml "${{ inputs.papermill-args-yaml }}"
