---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobset-controller-manager
  namespace: kubeflow-system
spec:
  selector:
    matchLabels:
      control-plane: jobset-controller-manager
  template:
    metadata:
      labels:
        control-plane: jobset-controller-manager
    spec:
      containers:
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
