apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where all resources are deployed.
namespace: kubeflow-system

resources:
  - namespace.yaml
  - ../../base/crds
  - ../../base/manager
  - ../../base/rbac
  - ../../base/webhook
  - ../../third-party/jobset # Comment this line if JobSet is installed on the Kubernetes cluster.

# Update the Kubeflow Training manager image tag.
images:
  - name: kubeflow/training-operator-v2
    newTag: latest

# Secret for the Kubeflow Training webhook.
secretGenerator:
  - name: training-operator-v2-webhook-cert
    namespace: kubeflow-system
    options:
      disableNameSuffixHash: true
