apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: status-server-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: manager
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          trainer.kubeflow.org/trainjob-namespace: "true"
      podSelector:
        matchLabels:
          trainer.kubeflow.org/trainjob-ancestor-step: trainer
    ports:
    - protocol: TCP
      port: 10443
