apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-deepspeed-demo
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: kubeflow/pytorch-deepspeed-demo:latest
              command:
                - torchrun
                - /train_bert_ds.py
                - --checkpoint_dir
                - /root/deepspeed_data
              resources:
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: kubeflow/pytorch-deepspeed-demo:latest
              command:
                - torchrun
                - /train_bert_ds.py
                - --checkpoint_dir
                - /root/deepspeed_data
              resources:
                limits:
                  nvidia.com/gpu: 1
