// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	applyconfigurationkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	scheme "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MPIJobsGetter has a method to return a MPIJobInterface.
// A group's client should implement this interface.
type MPIJobsGetter interface {
	MPIJobs(namespace string) MPIJobInterface
}

// MPIJobInterface has methods to work with MPIJob resources.
type MPIJobInterface interface {
	Create(ctx context.Context, mPIJob *kubefloworgv1.MPIJob, opts metav1.CreateOptions) (*kubefloworgv1.MPIJob, error)
	Update(ctx context.Context, mPIJob *kubefloworgv1.MPIJob, opts metav1.UpdateOptions) (*kubefloworgv1.MPIJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, mPIJob *kubefloworgv1.MPIJob, opts metav1.UpdateOptions) (*kubefloworgv1.MPIJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubefloworgv1.MPIJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubefloworgv1.MPIJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubefloworgv1.MPIJob, err error)
	Apply(ctx context.Context, mPIJob *applyconfigurationkubefloworgv1.MPIJobApplyConfiguration, opts metav1.ApplyOptions) (result *kubefloworgv1.MPIJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, mPIJob *applyconfigurationkubefloworgv1.MPIJobApplyConfiguration, opts metav1.ApplyOptions) (result *kubefloworgv1.MPIJob, err error)
	MPIJobExpansion
}

// mPIJobs implements MPIJobInterface
type mPIJobs struct {
	*gentype.ClientWithListAndApply[*kubefloworgv1.MPIJob, *kubefloworgv1.MPIJobList, *applyconfigurationkubefloworgv1.MPIJobApplyConfiguration]
}

// newMPIJobs returns a MPIJobs
func newMPIJobs(c *KubeflowV1Client, namespace string) *mPIJobs {
	return &mPIJobs{
		gentype.NewClientWithListAndApply[*kubefloworgv1.MPIJob, *kubefloworgv1.MPIJobList, *applyconfigurationkubefloworgv1.MPIJobApplyConfiguration](
			"mpijobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubefloworgv1.MPIJob { return &kubefloworgv1.MPIJob{} },
			func() *kubefloworgv1.MPIJobList { return &kubefloworgv1.MPIJobList{} },
		),
	}
}
