// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubefloworgv1 "github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1"
	applyconfigurationkubefloworgv1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/kubeflow.org/v1"
	scheme "github.com/kubeflow/training-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TFJobsGetter has a method to return a TFJobInterface.
// A group's client should implement this interface.
type TFJobsGetter interface {
	TFJobs(namespace string) TFJobInterface
}

// TFJobInterface has methods to work with TFJob resources.
type TFJobInterface interface {
	Create(ctx context.Context, tFJob *kubefloworgv1.TFJob, opts metav1.CreateOptions) (*kubefloworgv1.TFJob, error)
	Update(ctx context.Context, tFJob *kubefloworgv1.TFJob, opts metav1.UpdateOptions) (*kubefloworgv1.TFJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tFJob *kubefloworgv1.TFJob, opts metav1.UpdateOptions) (*kubefloworgv1.TFJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubefloworgv1.TFJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubefloworgv1.TFJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubefloworgv1.TFJob, err error)
	Apply(ctx context.Context, tFJob *applyconfigurationkubefloworgv1.TFJobApplyConfiguration, opts metav1.ApplyOptions) (result *kubefloworgv1.TFJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, tFJob *applyconfigurationkubefloworgv1.TFJobApplyConfiguration, opts metav1.ApplyOptions) (result *kubefloworgv1.TFJob, err error)
	TFJobExpansion
}

// tFJobs implements TFJobInterface
type tFJobs struct {
	*gentype.ClientWithListAndApply[*kubefloworgv1.TFJob, *kubefloworgv1.TFJobList, *applyconfigurationkubefloworgv1.TFJobApplyConfiguration]
}

// newTFJobs returns a TFJobs
func newTFJobs(c *KubeflowV1Client, namespace string) *tFJobs {
	return &tFJobs{
		gentype.NewClientWithListAndApply[*kubefloworgv1.TFJob, *kubefloworgv1.TFJobList, *applyconfigurationkubefloworgv1.TFJobApplyConfiguration](
			"tfjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubefloworgv1.TFJob { return &kubefloworgv1.TFJob{} },
			func() *kubefloworgv1.TFJobList { return &kubefloworgv1.TFJobList{} },
		),
	}
}
