name: Helm to Kustomize Sync Check

on:
  push:
    paths:
      - 'charts/**'
      - 'manifests/**'
      - 'scripts/helm_to_kustomize_sync.sh'
      - '.github/workflows/helm-kustomize-sync.yaml'
  pull_request:
    paths:
      - 'charts/**'
      - 'manifests/**'
      - 'scripts/helm_to_kustomize_sync.sh'
      - '.github/workflows/helm-kustomize-sync.yaml'
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if no changes detected'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync-check:
    name: Check Helm and Kustomize Synchronization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install yq
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Make sync script executable
        run: chmod +x scripts/helm_to_kustomize_sync.sh

      - name: Run sync script in dry-run mode
        run: |
          ./scripts/helm_to_kustomize_sync.sh \
            --dry-run \
            --verbose \
            --validate

      - name: Generate manifests to temporary directory
        id: generate
        run: |
          TEMP_DIR=$(mktemp -d)
          echo "temp_dir=${TEMP_DIR}" >> $GITHUB_OUTPUT

          ./scripts/helm_to_kustomize_sync.sh \
            --output-dir "${TEMP_DIR}" \
            --verbose

      - name: Compare with existing manifests
        id: compare
        run: |
          TEMP_DIR="${{ steps.generate.outputs.temp_dir }}"
          CHANGES_DETECTED=false

          # Compare base manifests
          if ! diff -r manifests/base "${TEMP_DIR}/base" > /dev/null 2>&1; then
            echo "Changes detected in base manifests"
            CHANGES_DETECTED=true
          fi

          # Compare overlays
          if ! diff -r manifests/overlays "${TEMP_DIR}/overlays" > /dev/null 2>&1; then
            echo "Changes detected in overlay manifests"
            CHANGES_DETECTED=true
          fi

          echo "changes_detected=${CHANGES_DETECTED}" >> $GITHUB_OUTPUT

          if [[ "${CHANGES_DETECTED}" == "true" ]]; then
            echo "::warning::Helm charts and Kustomize manifests are out of sync!"
            diff -r manifests "${TEMP_DIR}" || true
          else
            echo "✅ Helm charts and Kustomize manifests are in sync"
          fi

      - name: Validate Kustomize manifests
        run: |
          echo "Validating base manifests..."
          kubectl kustomize manifests/base > /dev/null

          echo "Validating standalone overlay..."
          kubectl kustomize manifests/overlays/standalone > /dev/null || true

          echo "Validating kubeflow-platform overlay..."
          kubectl kustomize manifests/overlays/kubeflow-platform > /dev/null || true

          echo "✅ All Kustomize manifests are valid"

      - name: Run tests
        run: |
          if [[ -f "scripts/tests/test_helm_to_kustomize.sh" ]]; then
            chmod +x scripts/tests/test_helm_to_kustomize.sh
            ./scripts/tests/test_helm_to_kustomize.sh
          else
            echo "Test script not found, skipping tests"
          fi

      - name: Create sync PR if changes detected
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          steps.compare.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync Kustomize manifests with Helm charts'
          title: '[Auto] Sync Kustomize manifests with Helm charts'
          body: |
            This PR automatically syncs Kustomize manifests with Helm chart changes.

            ## Changes detected
            The Helm charts have been modified and the Kustomize manifests need to be updated to stay in sync.

            ## Generated by
            - Workflow: `helm-kustomize-sync.yaml`
            - Script: `scripts/helm_to_kustomize_sync.sh`

            Please review the changes and merge if they look correct.
          branch: auto-sync/helm-kustomize
          delete-branch: true
          labels: |
            area/deployment
            kind/cleanup
            auto-generated

  validate-helm-chart:
    name: Validate Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: |
          helm lint charts/kubeflow-trainer

      - name: Template Helm chart
        run: |
          helm template test-release charts/kubeflow-trainer \
            --namespace kubeflow \
            --debug

      - name: Package Helm chart
        run: |
          helm package charts/kubeflow-trainer

  sync-on-schedule:
    name: Scheduled Sync Check
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 2 * * 1' # Run every Monday at 2 AM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Run comprehensive sync
        run: |
          chmod +x scripts/helm_to_kustomize_sync.sh
          ./scripts/helm_to_kustomize_sync.sh --validate --verbose

      - name: Check for drift
        run: |
          # Check if there are any uncommitted changes
          if [[ -n $(git status --porcelain manifests/) ]]; then
            echo "::error::Drift detected between Helm charts and Kustomize manifests!"
            git diff manifests/
            exit 1
          else
            echo "✅ No drift detected"
          fi