name: Unit and Integration Test - Rust

on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kubeflow/trainer' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: "pkg/data_cache"

      - name: Run Rust unit tests
        run: make test-rust
