name: Unit and Integration Test - Python

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  python-test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pytest python-dateutil urllib3 kubernetes
          pip install -U './sdk/python[huggingface]'

      - name: Run unit test for training sdk
        run: |
          pytest ./sdk/python/kubeflow/training/api/training_client_test.py

      - name: Run Python unit tests for v2
        run: |
          pip install -U './sdk_v2'
          export PYTHONPATH="${{ github.workspace }}:$PYTHONPATH"
          pytest ./pkg/initializer_v2/model
          pytest ./pkg/initializer_v2/dataset
          pytest ./pkg/initializer_v2/utils
