name: Test example notebooks

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-pytorchjob-notebook-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.28.7"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Setup E2E Tests
        uses: ./.github/workflows/setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}
          python-version: ${{ matrix.python-version }}

      - name: Run Jupyter Notebook with Papermill
        shell: bash
        run: |
          ./scripts/run-notebook.sh \
          -i ./examples/pytorch/image-classification/create-pytorchjob.ipynb \
          -o ./examples/pytorch/image-classification/create-pytorchjob-output.ipynb \
          -p "namespace default" \
          -k ./sdk/python
