name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

    strategy:
      fail-fast: false
      matrix:
        # Detail: `setup-envtest list`
        kubernetes-version: ["1.34.1", "1.35.0", "1.36.2"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator/go.mod

      - name: Run Go test for v1
        run: |
          make test ENVTEST_K8S_VERSION=${{ matrix.kubernetes-version }}
